openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 
    This is a documentation of Contacts app
tags:
  - name: Students
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:4000
  - url: https://node-js-hw-2-mongodb.onrender.com/
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/path/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer